# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['192.168.0.10:9090']

  - job_name: 'netdata'

    metrics_path: /api/v1/allmetrics
    params:
      format: [ prometheus ]

    static_configs:
      - targets: ["192.168.0.10:19999", "192.168.0.24:19999", "192.168.0.24:29999", "192.168.0.26:19999", "192.168.0.27:19999", "192.168.0.28:19999", "192.168.0.26:29999", "192.168.0.27:29999", "192.168.0.28:29999", "192.168.0.195:19999", "192.168.0.195:29999"]

  - job_name: docker
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

    static_configs:
      # lambda, hydra-3, hydra-2, hydra-1, hydra-?:vastai-docker
      - targets: ["192.168.0.10:9323", "192.168.0.24:9323", "192.168.0.24:19323", "192.168.0.26:9323", "192.168.0.26:19323", "192.168.0.27:9323", "192.168.0.27:19323", "192.168.0.28:9323", "192.168.0.28:19323"]

  - job_name: cadvisor
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

    static_configs:
      - targets: ["192.168.0.10:8080", "192.168.0.24:8080", "192.168.0.26:8080", "192.168.0.27:8080", "192.168.0.28:8080"]

  - job_name: vastai
    static_configs:
      - targets: ["192.168.0.10:8622"]

  - job_name: vastai_global
    metrics_path: /metrics/global
    static_configs:
      - targets: ["192.168.0.10:8622"]                                                                                                                                                                   

  - job_name: nvidia
    static_configs:
      - targets: ["192.168.0.10:9400", "192.168.0.24:19400", "192.168.0.26:9400", "192.168.0.27:9400", "192.168.0.28:9400"]

  - job_name: vastai_offers
    metrics_path: /
    scrape_interval: 1m
    scrape_timeout: 30s
    static_configs:
      - targets: ["192.168.0.10:8888"]

  - job_name: journald-exporter
    basic_auth:
      username: metrics
      password_file: /etc/prometheus/journald-exporter.key
    scheme: http
    static_configs:
      - targets: ["192.168.0.195:12345"] 

